# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e0ec235eeb5cd47e74d3ce0ee727a5be36946dd543995d48b2bd588d1e964b37a19b277e6634868ea76cc4d6534f9af182ffcc2eeca80009d13530bf2675a62

test:
  secret_key_base: a94fad293daedb47d3efa1f75335ed22de039600645a462a3ce16014b2fff373c8a69187346ed8d947d0dcf1d0e244f8f647fd7acef9a04d8ac18f87a6afd98f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
